Metrics/MethodLength:
  Max: 15
  CountAsOne: [array, hash, heredoc]

Metrics/AbcSize:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Include:
    - "**/*.rb"
